# Generated by Django 4.2.11 on 2024-03-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(error_messages={'unique': '이미 등록된 학번입니다'}, max_length=10, unique=True),
        ),
    ]
