# Generated by Django 4.2.11 on 2024-03-12 05:23

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_user_student_id_user_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(error_messages={'unique': '이미 등록된 이름입니다'}, max_length=10, validators=[posts.validators.validate_no_special_characters]),
        ),
    ]
