# Generated by Django 4.2.11 on 2024-03-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_pic',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to='user_pics'),
        ),
    ]
