# Generated by Django 4.2.11 on 2024-03-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_user_user_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
